qbankproject/urls.py
from django.contrib import admin
from django.urls import path,include
from mainapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('',views.home,name='home'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('addquestion/', views.addquestion, name='addquestion'),
    path('qverify/',views.qverify,name='qverify'),
    path('search/',views.search,name='search'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('qfeedback/<int:id>',views.qfeedback,name='qfeedback'),
    path('feedget/',views.feedget,name='feedget'),
    path('category/',views.category,name='category'),
    path('sort/',views.sort,name='sort'),
    path('print/',views.print_f,name='print_f'),
    path("__reload__/", include("django_browser_reload.urls")),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import *


urlpatterns = [
	path('signup/', signup, name = 'signup'),
	path('login/', login_view, name = 'login'),
	path('logout/', LogoutView.as_view(next_page = 'login'), name = 'logout'),

	path("password-reset/", 
    	PasswordResetView.as_view(template_name='user/password_reset.html'),
    	name="password_reset"),

	path("password-reset/done/", 
		PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), 
		name="password_reset_done"),

	path("password-reset-confirm/<uidb64>/<token>/", 
		PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), 
		name="password_reset_confirm"),

	path("password-reset-complete/", 
		PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), 
		name="password_reset_complete"),

]

mainapp/models.py
from django.db import models


# Create your models here.
class university(models.Model):
    university_name = models.CharField(max_length=100)
    def __str__(self):
        return self.university_name

class department(models.Model):
    university = models.ForeignKey(university, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    def university_name(self):
        return self.university.university_name
    def __str__(self):
        return self.name

class subject(models.Model):
    department = models.ForeignKey(department, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    def department_name(self):
        return self.department.name
    def __str__(self):
        return self.subject

class questionanswer(models.Model):
    ques= models.TextField()
    answer=models.TextField()
    username=models.CharField(max_length=100)
    university_select = models.ForeignKey(university, on_delete=models.CASCADE)
    department = models.ForeignKey(department, on_delete=models.CASCADE)
    subject = models.ForeignKey(subject, on_delete=models.CASCADE)
    semester=models.CharField(max_length=25)
    year=models.IntegerField()
    show=models.BooleanField(default=False)
    timesAsked=models.CharField(max_length=2,blank=True,null=True)
    comment=models.CharField(max_length=500,null=True)
    important=models.BooleanField(default=False)
    def __str__(self):
        return self.ques[:30]

class feedback_m(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    message=models.TextField()
    def __str__(self):
        return self.message[13:30]

theme/templates/addQ.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
{% endblock %}
Add question
{% block title %}
Question bank
{% endblock title %}
{% block style %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<link href="{% static 'css/base.css' %}" rel="stylesheet">
{% endblock style %}
{% block content %}
<main class="min-h-screen">
    <div class="pt-44 lg:pt-28 pb-8 flex ">
        <div class="w-full ">
            <div>
                <h1 class="text-2xl mx-10 lg:mx-52 mb-4 text-slate-700">Add Questions</h1>
                {% if user.is_authenticated %}
                {% else %}
                <h4 class="text-red-600 mx-12 lg:mx-56 text-lg">Please login to add questions</h4>
                {% endif %}
            </div>
            <div class="mx-12 lg:mx-56">
                <form action="." method="post">
                    {% csrf_token %}
                    <label for="ques" class="text-lg text-slate-700">Question <span
                            class="text-red-600">*</span></label>
                    {{form.ques}}
                    <label for="answer" class="text-lg text-slate-700">Answer <span
                            class="text-red-600">*</span></label>
                    {{form.answer}}
                    <label for="id_university_select" class="text-lg text-slate-700">University <span
                            class="text-red-600">*</span></label>
                    {{form.university_select}}
                    <label for="id_department_select" class="text-lg text-slate-700">Department <span
                            class="text-red-600">*</span></label>
                    {{form.department_select}}
                    <label for="subject" class="text-lg text-slate-700">Subject <span
                            class="text-red-600">*</span></label>
                    {{form.subject}}
                    <label for="semester" class="text-lg text-slate-700">Semester <span
                            class="text-red-600">*</span></label>
                    {{form.semester}}
                    <div class="lg:flex justify-between">
                        <div class="mr-5 w-full">
                            <label for="year" class="text-lg text-slate-700">Year <span
                                    class="text-red-600">*</span></label>
                            {{form.year}}
                        </div>
                        <div class=" mb-2 w-full">
                            <label for="timesAsked" class="text-lg text-slate-700">Times asked(optional) </label>
                            {{form.timesAsked}}
                        </div>
                    </div>
                    <label for="comment" class="text-lg text-slate-700">Comments</label>
                    {{form.comment}}
                    {{form.important}}
                    <label for="id_important">This question important</label><br>
                    <input type="checkbox" name="terms" id="terms" required> I Agree this question was asked on
                    mentioned date <br><br>
				{% if user.is_authenticated %}
                    <input type="submit" value="Submit" id="submit"
                        class="text-white lg:w-2/5 w-36 h-10 bg-slate-700 rounded">
                    <input type="reset" class="text-white w-36 lg:w-2/5 h-10 bg-slate-700 rounded">
                    {% else %}
                    <h4 class="text-red-600 text-lg">Please login to add questions</h4>
                    {% endif %}
                </form>
            </div>
        </div>
        <div></div>
    </div>
    <div></div>
</main>
{% block js %}
{% include "js2.html" %}
{% endblock %}
{% endblock %}

theme/templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}
		Question bank
		{% endblock title %}</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<!-- delete below 2 lines after finishing addQ -->
	{% block style %}
	{% endblock style %}

	{% tailwind_css %}
</head>

<body class="bg-gray-50 font-sans leading-normal tracking-normal">
	<!-- navbar -->
	<div class="w-full border-b-2 shadow-lg fixed bg-white z-30">
		<div class="md:absolute md:block text-white dark:text-black hidden"><a class=" cursor-default" href="/admin">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></div>
		<nav class="flex items-center justify-between flex-wrap p-5  sm:mx-5 md:mx-6">


			<div class="flex items-center flex-shrink-0 text-slate-700 lg:ml-auto ml-5  sm:ml-0 mr-5">
				<span class="text-4xl lg:text-2xl font-bold tracking-tight"><a href="/">Question
						Bank</a></span>
			</div>

			<svg id="burger" xmlns="http://www.w3.org/2000/svg"
				class="h-6 w-6 text-black lg:hidden  hover:cursor-pointer" fill="none" viewBox="0 0 24 24"
				stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
			</svg>
			<div id="menu"
				class="w-full  hidden  text-black flex-grow lg:flex lg:items-center lg:w-auto ml-3 lg:ml-0 mt-1">
				<div class="text-lg md:flex-grow">
					<a href="/addquestion"
						class=" block lg:inline-block lg:mt-0 mt-3 lg:text-lg text-xl font-medium lg:font-normal text-slate-600 hover:text-black mr-4">
						Add question
					</a>
					<a href="/feedback"
						class=" block lg:inline-block lg:mt-0 mt-3 lg:text-lg text-xl font-medium lg:font-normal text-slate-600 hover:text-black mr-4">
						Feedback
					</a>
					<a href="/about"
						class="lg:mb-0 block lg:inline-block lg:mt-0 my-3 lg:text-lg text-xl font-medium lg:font-normal text-slate-600 hover:text-black">
						About
					</a>
				</div>
				{% if user.is_authenticated %}
				<h4 class="mr-8 text-lg text-slate-600 hidden sm:block">Hello <span class="font-semibold">{{user.username}}!</span></h4>
				<div class=" lg:flex lg:bg-slate-600 transition ease-in-out duration-300 hover:bg-slate-700 rounded">
					<a href="{% url 'logout' %}"
						class=" lg:inline lg:mb-0 lg:px-5 lg:py-2 leading-none rounded font-medium lg:font-normal text-slate-600 lg:text-slate-50 text-xl lg:text-lg lg:mt-0">Log
						out</a>
				</div>

				{% else %}
				<div class=" lg:flex lg:bg-slate-600 transition ease-in-out duration-300 hover:bg-slate-700 rounded">

					<a href="{% url 'login' %}"
						class=" lg:inline lg:mb-0 lg:px-5 lg:py-2 leading-none rounded font-medium lg:font-normal text-slate-600 lg:text-slate-50 text-xl lg:text-lg lg:mt-0">Log
						in</a>
				</div>
				{% endif %}
			</div>
		</nav>
	</div>
	<!-- navend -->
	{% block content %}

	{% endblock %}
	<!-- footer -->
	<footer class="w-auto p-4 bottom-0 h-auto relative bg-gray-600 ">
		<div class="lg:flex  lg:mt-3 md:mx-12 lg:mx-28 lg:justify-between">
			<div class="mb-4 lg:columns-1 md:w-96">
				<p class="text-white font-bold mb-1 mt-3">About Us</p>
				<p class="text-gray-200 text-sm">We value diversity and belive that different backgrouds, ideas and
					perspectives are what makes us stronger and more capable as a team. Each and every one of us adds to
					our mission. We blend our strengths togehter, combining our experience and creative minds to bring
					the best ideas.
				</p>
			</div>
			<div class="mb-4  lg:mt-3">
				<h3 class="text-white font-bold mb-2 lg:mb-4"> Social Media</h3>
				<div class="">
					<div class=" flex lg:items-center ">
						<div class="lg:container lg:max-w-screen-lg ">
							<div>
								<div class="lg:flex lg:flex-wrap gap-2 ">

									<a href="https://github.com/ilyasbabu/questio-bank-django">
										<button
											class="bg-gray-700 hover:bg-white hover:text-black  p-2 font-semibold text-white inline-flex items-center space-x-2 rounded">
											<svg xmlns="http://www.w3.org/2000/svg"
												xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img"
												class="w-5" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
												<g fill="none">
													<path fill-rule="evenodd" clip-rule="evenodd"
														d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385c.6.105.825-.255.825-.57c0-.285-.015-1.23-.015-2.235c-3.015.555-3.795-.735-4.035-1.41c-.135-.345-.72-1.41-1.23-1.695c-.42-.225-1.02-.78-.015-.795c.945-.015 1.62.87 1.845 1.23c1.08 1.815 2.805 1.305 3.495.99c.105-.78.42-1.305.765-1.605c-2.67-.3-5.46-1.335-5.46-5.925c0-1.305.465-2.385 1.23-3.225c-.12-.3-.54-1.53.12-3.18c0 0 1.005-.315 3.3 1.23c.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23c.66 1.65.24 2.88.12 3.18c.765.84 1.23 1.905 1.23 3.225c0 4.605-2.805 5.625-5.475 5.925c.435.375.81 1.095.81 2.22c0 1.605-.015 2.895-.015 3.3c0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z"
														fill="currentColor" />
												</g>
											</svg>
										</button>
									</a>
									<a href="">
										<button
											class="bg-blue-400 p-2 hover:bg-white hover:text-black font-semibold  text-white inline-flex items-center space-x-2 rounded">
											<svg class="w-5 h-5 fill-current" role="img"
												xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
												<path
													d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z" />
											</svg>
										</button>
									</a>
									<a href="">
										<button
											class="bg-red-500 p-2 hover:bg-white hover:text-black font-semibold text-white inline-flex items-center space-x-2 rounded">
											<svg class="w-5 h-5 fill-current" role="img" viewBox="0 0 24 24"
												xmlns="http://www.w3.org/2000/svg">
												<path
													d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0zm5.01 4.744c.688 0 1.25.561 1.25 1.249a1.25 1.25 0 0 1-2.498.056l-2.597-.547-.8 3.747c1.824.07 3.48.632 4.674 1.488.308-.309.73-.491 1.207-.491.968 0 1.754.786 1.754 1.754 0 .716-.435 1.333-1.01 1.614a3.111 3.111 0 0 1 .042.52c0 2.694-3.13 4.87-7.004 4.87-3.874 0-7.004-2.176-7.004-4.87 0-.183.015-.366.043-.534A1.748 1.748 0 0 1 4.028 12c0-.968.786-1.754 1.754-1.754.463 0 .898.196 1.207.49 1.207-.883 2.878-1.43 4.744-1.487l.885-4.182a.342.342 0 0 1 .14-.197.35.35 0 0 1 .238-.042l2.906.617a1.214 1.214 0 0 1 1.108-.701zM9.25 12C8.561 12 8 12.562 8 13.25c0 .687.561 1.248 1.25 1.248.687 0 1.248-.561 1.248-1.249 0-.688-.561-1.249-1.249-1.249zm5.5 0c-.687 0-1.248.561-1.248 1.25 0 .687.561 1.248 1.249 1.248.688 0 1.249-.561 1.249-1.249 0-.687-.562-1.249-1.25-1.249zm-5.466 3.99a.327.327 0 0 0-.231.094.33.33 0 0 0 0 .463c.842.842 2.484.913 2.961.913.477 0 2.105-.056 2.961-.913a.361.361 0 0 0 .029-.463.33.33 0 0 0-.464 0c-.547.533-1.684.73-2.512.73-.828 0-1.979-.196-2.512-.73a.326.326 0 0 0-.232-.095z" />
											</svg>
										</button>
									</a>
									<a href="">
										<button
											class="bg-blue-600 p-2 hover:bg-white hover:text-black font-semibold text-white inline-flex items-center space-x-2 rounded">
											<svg class="w-5 h-5 fill-current" role="img" viewBox="0 0 256 256"
												xmlns="http://www.w3.org/2000/svg">
												<g>
													<path
														d="M218.123122,218.127392 L180.191928,218.127392 L180.191928,158.724263 C180.191928,144.559023 179.939053,126.323993 160.463756,126.323993 C140.707926,126.323993 137.685284,141.757585 137.685284,157.692986 L137.685284,218.123441 L99.7540894,218.123441 L99.7540894,95.9665207 L136.168036,95.9665207 L136.168036,112.660562 L136.677736,112.660562 C144.102746,99.9650027 157.908637,92.3824528 172.605689,92.9280076 C211.050535,92.9280076 218.138927,118.216023 218.138927,151.114151 L218.123122,218.127392 Z M56.9550587,79.2685282 C44.7981969,79.2707099 34.9413443,69.4171797 34.9391618,57.260052 C34.93698,45.1029244 44.7902948,35.2458562 56.9471566,35.2436736 C69.1040185,35.2414916 78.9608713,45.0950217 78.963054,57.2521493 C78.9641017,63.090208 76.6459976,68.6895714 72.5186979,72.8184433 C68.3913982,76.9473153 62.7929898,79.26748 56.9550587,79.2685282 M75.9206558,218.127392 L37.94995,218.127392 L37.94995,95.9665207 L75.9206558,95.9665207 L75.9206558,218.127392 Z M237.033403,0.0182577091 L18.8895249,0.0182577091 C8.57959469,-0.0980923971 0.124827038,8.16056231 -0.001,18.4706066 L-0.001,237.524091 C0.120519052,247.839103 8.57460631,256.105934 18.8895249,255.9977 L237.033403,255.9977 C247.368728,256.125818 255.855922,247.859464 255.999,237.524091 L255.999,18.4548016 C255.851624,8.12438979 247.363742,-0.133792868 237.033403,0.000790807055">
													</path>
												</g>
											</svg>
										</button>
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="lg:mt-3 mb-4">
				<h3 class="text-white font-bold mb-2 lg:mb-2">Navigate</h3>
				<div class="columns-2 md:columns-3 lg:columns-2">
					<a class="text-gray-200" href="/addquestion">Add question</a><br>
					<a href="index.html" class="text-gray-200">Find Questions</a><br>
					<a class="text-gray-200" href="/feedback">Feedback</a><br>
					<a class="text-gray-200" href="login.html">Sign up/Login</a><br>
					<a href="/about" class="text-gray-200">About</a><br>
					<a href="/about" class="text-gray-200">Contact</a><br>
				</div>
			</div>
		</div>
		<div>
			<div class="flex justify-center mt-2">
				<p class="text-gray-400"> Copyright &copy;
					<script>document.write(new Date().getFullYear());</script> All rights reserved
				</p>
			</div>
		</div>
	</footer>
	<!-- footerend -->
	<script src="{% static 'js/script.js' %}"></script>
</body>
{% block js %}{% endblock %}

</html>

theme/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Question bank
{% endblock title %}

{% block style %}
<style>
    table,
    th,
    td {
        border: 1px solid black;
        padding: 15px;
    }
</style>
{% endblock style %}

{% block content %}


<div class="py-40 px-12">
    <table class="">
        <tr>
            <th>Question</th>
            <td>{{qu.ques}}</td>
        </tr>
        <tr>
            <th>Answer</th>
            <td>{{qu.answer}}</td>
        </tr>
        <tr>
            <th>University</th>
            <td>{{qu.university_select}}</td>
        </tr>
        <tr>
            <th>Department</th>
            <td>{{qu.department}}</td>
        </tr>
        <tr>
            <th>Subject</th>
            <td>{{qu.subject}}</td>
        </tr>
        <tr>
            <th>Semester</th>
            <td>{{qu.semester}}</td>
        </tr>
        <tr>
            <th>Year</th>
            <td>{{qu.year}}</td>
        </tr>
        <tr>
            <th>Times asked</th>
            <td>{{qu.timesAsked}}</td>
        </tr>
        <tr>
            <th>Added by</th>
            <td>{{qu.username}}</td>
        </tr>
    </table>
    <div class="py-2 pl-2">
        <a href="/" class="text-blue-700 underline font-medium">Return to homepage</a>
    </div>
    <div class="py-2 pl-2">
        <a href="/qfeedback/{{qu.id}}" class="text-blue-700 underline font-medium">Send feedback on this question</a>
    </div>
</div>



{% endblock content %}

theme/templates/feedback.html
{% extends 'base.html' %}
{% block title %}
Feedback
{% endblock title %}
{% block content %}


<section class="text-gray-600 body-font relative pt-14 min-h-screen">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-8">
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-slate-700">Feedback</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base text-slate-700">Feel free to write to us.</p>
        </div>
        <div class="lg:w-1/2 md:w-2/3 mx-auto">
            <div>
                <form action="/feedget/" method="post" class="flex flex-wrap -m-2">
                    {% csrf_token %}
                    <div class="p-2 w-1/2">
                        <div class="relative">
                            <label for="name" class="leading-7 text-sm text-gray-600">Name</label>
                            <input type="text" id="name" name="name"
                                class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-500 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                                placeholder="Your Name"
                                required>
                        </div>
                    </div>
                    <div class="p-2 w-1/2">
                        <div class="relative">
                            <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
                            <input type="email" id="email" name="email"
                                class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-500 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                                placeholder="example@email.com"
                                required>
                        </div>
                    </div>
                    <div class="p-2 w-full">
                        <div class="relative">
                            <label for="message" class="leading-7 text-sm text-gray-600">Message</label>
                            <textarea id="message" name="message" required
                                class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-500 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out">{% if qu %}Feedback for question id=[{{qu.id}}]: (write your feedback after this text)
                                {% endif %}</textarea>
                        </div>
                    </div>
                    <div class="p-2 w-full">
                        <input type="submit" value="Send"
                            class="flex mx-auto text-white bg-slate-600 border-0 py-2 px-16 focus:outline-none hover:bg-slate-700 rounded text-lg">
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock %}

theme/templates/js2.html
{% block js %}
<script language="javascript">
    $('#id_university_select').change(function() {populateCar(this)});
    // $('#id_subject').addClass('subjects');

    departments= {{ form.departments | safe }}
    universitys= {{ form.universitys | safe }}
    universitysid={{ form.universitysid | safe }}
    departmentsid={{ form.deptid | safe }};
    populateBrand();
    $("#id_department_select").empty();
    $("#id_department_select").append('<option value="" disabled selected>First select a university</option>');


    function populateBrand() {
        $('#id_university_select').empty();
        $("#id_university_select").append('<option value="" disabled selected>Select your option</option>');
        $.each(universitys, function(v) {
            $('#id_university_select')
                .append($("<option></option>")
                .attr("value", universitysid[v])
                .text(universitys[v]));
        });
    }

    function populateCar(event) {
        universitys = $("#id_university_select option:selected").text();
        $("#id_department_select").empty();
        $("#id_department_select").append('<option value="" disabled selected>Select your option</option>');
        for (let [b, bdepartments] of Object.entries(departmentsid)) {
            if (b == universitys) {
                //alert(b);

                for (department in bdepartments) {
                    
                    $('#id_department_select')
                        .append($("<option></option>")
                            .attr("value", bdepartments[department])
                            .text(departments[b][department]));
                }
            }
        }
    }
</script>
{% endblock %}

theme/templates/login.html
{% extends 'base.html' %}
{% block title %}
temperory
{% endblock title %}
{% block content %}
<div class="flex justify-center ">
    <div class="shadow-2xl h-screen lg:w-1/2 w-full drop-shadow-xl flex justify-center items-center">
        <div>

            <form action="." method="post">
                {% csrf_token %}
                <div>
                    <span class="text-sm text-slate-700">Welcome back</span>
                    <h1 class="text-2xl text-slate-600 font-bold">Login to your account</h1>
                </div>
                <div class="my-3">
                    <label class="block text-md mb-2 text-slate-700" for="username">Username</label>
                    <input class="px-4 w-full border-2 py-2 rounded-md text-sm outline-none" type="text" name="username"
                        placeholder="joe">
                </div>
                <div class="mt-5">
                    <label class="block text-md mb-2 text-slate-700" for="password">Password</label>
                    <input class="px-4 w-full border-2 py-2 rounded-md text-sm outline-none" type="password"
                        name="password" placeholder="**********">
                </div>

                <div class="flex justify-between">
                    <div>
                        <input class="cursor-pointer" type="radio" name="rememberme">
                        <span class="text-sm text-slate-700">Remember Me</span>
                    </div>
                    <span class="text-sm text-blue-700 hover:underline cursor-pointer">Forgot password?</span>
                </div>
                <div class="">
                    <button type="submit"
                        class="mt-4 mb-3 w-full bg-slate-500 hover:bg-green-400 text-white py-2 rounded-md transition duration-100">Login
                        now</button>
                    {% for i in messages %}
                    <h4 class="text-red-600">{{ i }}</h4>
                    {% endfor %}

                </div>
            </form>
            <p class="mt-4 text-slate-700"> Dont have an account? <span class="cursor-pointer text-sm text-blue-600"> <a
                        href="/create_acc"> Create account!</a></span></p>
        </div>
    </div>
</div>

{% endblock %}

theme/templates/q_verify_prompt.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Question bank
{% endblock title %}
{% block content %}

<div class="md:flex md:align-middle md:justify-center h-screen w-full  md:items-center ">
    <div class="bg-slate-50 md:px-96 md:py-12 shadow-2xl">
        <h6 class="text-xl">Your Question has been submitted for verification and will be verifiewd in 24 hrs</h6>
        <br>
        <a href="/" class="text-blue-800 underline">return to homepage</a>
    </div>
</div>

{% endblock %}